version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  pytest: 
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests

          command: python -m pytest

workflows:
  tests:
    jobs:
      - pytest